name: main-guard

on:
  push:
    branches: [$default-branch]

permissions: {}

jobs:
  guard:
    uses: isaacmoura/workflows/.github/workflows/main-guard.yml@v1
    permissions:
      contents: read
      pull-requests: read
      issues: write
      checks: read
